# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME = "vagrant-ubuntu"
Vagrant.configure("2") do |config|
  config.vm.define HOSTNAME do |i|
    # Configure box
    i.vm.box = "ubuntu/focal64"

    # Configure VM
    i.vm.hostname = HOSTNAME
    # i.vm.network "public_network", bridge: [ "eth0" ]
    # i.vm.network "public_network", bridge: [ "wlan0" ]
    i.vm.network :forwarded_port, guest: 22, host: 2242
    i.vm.synced_folder "./", "/vagrant"
    # i.vm.provision "shell", path: 'install-software.sh'
    i.vm.provision "shell", inline: "apt-get update"
    i.vm.provision "shell", inline: "apt-get install -y ruby"
    i.vm.provision "shell", path: "install-software.rb"

    # Configure provider
    i.vm.provider "virtualbox" do |v|
      v.name = HOSTNAME
      v.memory = 2048
    end
  end
end
